# Generated by Django 4.1.5 on 2023-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
