# Generated by Django 4.1.5 on 2023-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_blogcategory_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
