# Generated by Django 4.1.5 on 2023-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_image'),
        ),
    ]
