# Generated by Django 4.1.5 on 2023-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_contactform_created_on_homepage_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('project_name', models.CharField(blank=True, max_length=250, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
