# Generated by Django 4.1.5 on 2023-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_ourproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='personal_image'),
        ),
    ]
