# Generated by Django 4.1.5 on 2023-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_homepage_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='project_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='skill_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
