# Generated by Django 4.1.5 on 2023-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_homepage_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_us_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
