# Generated by Django 4.1.5 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_homepage_contact_us_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='resume_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
