# Generated by Django 4.1.5 on 2023-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_alter_homepage_resume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
