# Generated by Django 4.1.5 on 2023-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_service_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_me_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
